### ISSUE TITLE
Any suggestions to use with logical operations?

### ISSUE THREAD

**Issue by offminded** [jonschlinkert/handlebars-delimiters#1]
Delimiter was a great helper so far. I am kinda stuck with a problem tho, I have some logical operations such as:
`{{#if blabla}} {{/if}}`
`{{#each blabla}} {{/each}}`

and includes like:
`{{>menu}}`

and is delimiter acting weird with these. For ex, if I am including a content as below:
`<%=>header %>`
`<%=>menu %>`
`<%=>footer %>`

header content is getting compiled 3 times, instead of menu and footer. Switching back to regular delimiter correctly compiles each content item.

Any suggestions? Thanks.

**Comment by jonschlinkert** [comment]
hmm, sounds like the compiled function is being reused instead of being updated. can you give a longer example for me to mess around with?

**Comment by offminded** [comment]
Sure, here is a simplified version:

First I register partials to Handlebars library (header.html, menu.html, footer.html):

```
var fs = require('fs');
var Handlebars = require('handlebars');

var registerPartials = function () {
var partials = fs.readdirSync('views/partials'),
html;
for (var i = partials.length - 1; i >= 0; i--) {
    html = fs.readFileSync('views/partials/' + partials[i], 'utf-8');
    Handlebars.registerPartial(partials[i].replace(/.html/, ''), html);
    }
};
```

At this point 3 partials are registered as header, menu, footer. 

I pass all template data to a json file
`var data = JSON.parse(fs.readFileSync('data/data.json'));`

My source is just simple partial includes

```
{{> header}
{{> menu}}
{{> footer}}
```

Lastly stringify json data and compile it with handlebars:

```
var assemble = function(file, enc, cb){
    registerPartials();
    var source = file.contents.toString(),
    template = Handlebars.compile(source),
    html = template(data);
    file.contents = new Buffer(html);
    this.push(file);
    cb();
}
```

Normally with handlebars template gets compiled correctly:

```
<!-- template -->
<p>this is header content</p>
<p>this is menu content</p>
<p>this is footer content</p>
```

but with delimiters...
`useDelims(Handlebars, ['<%=', '%>']);`

```
<%=>header%>
<%=>menu%>
<%=>footer%>
```

the first partial gets rendered 3 times:

```
<!-- template -->
<p>this is header content</p>
<p>this is header content</p>
<p>this is header content</p>
```

**Comment by offminded** [comment]
Anyway I have switched to nunjucks and used its custom delimiters. Thanks.

**Comment by stefan-wiesner** [comment]
This issue should not be closed. It is still existing. Moving to another Engine is not solving the issue itself.

**Comment by jonschlinkert** [comment]
create a new issue please

**Comment by kjwenger** [comment]
... that seems to be a bug which I would like to get fixed since it is an easy enough one:

`handlebars-delimiters/index.js#35`
```
    while (match = re.exec(args[0])) {
      args[0] = args[0].replace(match[0], '{{' + match[1] + '}}');
    }
```
